name: Build main

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [8.0.x, 9.0.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        id: stepid
        with:
          dotnet-version: |
            9.0.x
            8.0.x
      - name: Install local tools
        run: dotnet tool restore
      - name: Restore Solution
        run: dotnet restore
      - name: Build
        run: dotnet fsi tools.fsx
      - name: Prepare Esbuild
        run: dotnet fsi esbuild-ci.fsx
      - name: Test
        run: dotnet fsi tools.fsx -- test
